### ISSUE TITLE
Curvature rate definition when "inverting" clothoid

### ISSUE THREAD

**Issue by mander76** [phillipd94/pyclothoids#4]
Hi, first of all thanks a bunch for this package it's great! And we are using it (as my colleague Irene already said) in our package **scenariogeneration**. 

I have one question that caused me some headache (might be me who don't understand fully the definitions. 

In our package we sometimes want to calculate the "inverted" clothoid (so we know the end point instead of the start point), however this caused a problem (that the previous method we used didn't have). I made a simple example to explain

```
import pyclothoids as pcloth

import numpy as np
curvature_0 = 0.0001
curvature_rate = 0.0001
x = 0
y = 0
h = 0
length = 100


cloth_1 = pcloth.Clothoid.StandardParams(x, y, h, curvature_0, curvature_rate, length)

print(cloth_1.XEnd, cloth_1.YEnd, cloth_1.ThetaEnd,cloth_1.KappaStart,cloth_1.KappaEnd)

cloth_2 = pcloth.Clothoid.StandardParams(cloth_1.XEnd, cloth_1.YEnd, cloth_1.ThetaEnd+np.pi, -cloth_1.KappaEnd, -curvature_rate, length)

print(cloth_2.XEnd, cloth_2.YEnd, cloth_2.ThetaEnd,cloth_2.KappaStart,cloth_2.KappaEnd)
```

So a simple example where I use a clothoid to calculate the end point, then use that endpoint to back track (and expect the same results).

What confuses me here is the curvature_rate, if I have is the example (in cloth_2), I would assume that the curvature_rate should be negative to come back to the original point, but that is not the case. it requires a positive curvature rate as

```
cloth_2 = pcloth.Clothoid.StandardParams(cloth_1.XEnd, cloth_1.YEnd, cloth_1.ThetaEnd+np.pi, -cloth_1.KappaEnd, curvature_rate, length)
```
to return to the correct start point. 

Have I missed something fundamental, or is this a bug somewhere?

**Comment by phillipd94** [comment]
While a bit counterintuitive, the curvature rates in the package are correct mathematically.  The reason this is counterintuitive is because when a clothoid is "inverted" this way, the curvature rate undergoes two sign-changing transformations that ultimately cancel out.  I'll try to make sense of it using intuition instead of burdensome equations here, apologies if it comes out a bit seeming a bit arcane:

When you flip directions this way, the sign of the curvature changes because while you are still on the same "osculating circle" at each point, you are now instantaneously rotating clockwise instead of counterclockwise.  This is why the initial curvature changed signs.  However, the directionality of the arc length "s" also changes, because the end point of the old clothoid is the start point of the new clothoid.  So as the arc length increases, you move in the opposite direction along the new curve as you did on the old curve, so in the case of the curvature rate, the sign flips again.  To be more specific, the curvature rate is the derivative of the curvature with respect to arc length, so dk/ds.  Both "k" and "s" changed signs, so the new clothoid's curvature rate would be -dk/-ds = dk/ds.  

You can sanity check this reasoning easily with an example.  Consider a clothoid curve that starts with zero curvature, but ends with 1 curvature.  If we invert that clothoid, the new clothoid will start with -1 curvature and end with zero curvature.  For both cases, the starting curvature is less than the ending curvature, so in both cases the curvature rate must be positive.

Now, about fixing your headaches.  The case you're describing is definitely a "gotcha", despite being technically correct, so pyclothoids includes a dedicated method to do the exact task you're describing.  If you call Clothoid.Reverse(), you will get the correctly reversed (or inverted) clothoid as you want, without needing to fuss with the sign conventions yourself.  The inversion also takes place on the C++ layer of the code if you use the library function, so I suspect it will be more performant as well (though I did see some vanishingly small numerical differences between your code and the library function, on the order of 10^-14).  Try this:

```
import pyclothoids as pcloth

import numpy as np
curvature_0 = 0
curvature_rate = 1
x = 0
y = 0
h = 0
length = 5

cloth_1 = pcloth.Clothoid.StandardParams(x, y, h, curvature_0, curvature_rate, length)

print(cloth_1.XEnd, cloth_1.YEnd, cloth_1.ThetaEnd,cloth_1.KappaStart,cloth_1.KappaEnd)

cloth_2 = pcloth.Clothoid.StandardParams(cloth_1.XEnd, cloth_1.YEnd, cloth_1.ThetaEnd+np.pi, -cloth_1.KappaEnd, curvature_rate, length)

print(cloth_2.XEnd, cloth_2.YEnd, cloth_2.ThetaEnd,cloth_2.KappaStart,cloth_2.KappaEnd)

cloth_3 = cloth_1.Reverse()

print(cloth_3.XEnd, cloth_3.YEnd, cloth_3.ThetaEnd,cloth_3.KappaStart,cloth_3.KappaEnd)
```

Let me know if there's any other concerns, or if this clears it up.

**Comment by mander76** [comment]
Thanks for the quick reply!

I follow what you mean and can accept it ;) 

Now for our use case (not exactly me example sadly enough was more of a showcase for the problem at hand). We are patching different geometries together and therefore we have a two step definition of all geometries (including the Clothoid):

1. give length, curvature_start, and curvature_end (get the rate from this)
2. give a start or end point of the clothoid and calculate for the one missing. So the reverse method will not work in this case since I cannot give any x,y,h info for the calculation, 

Hence it depends on if we get the start or end point if we want to revert it or not. But with this explanation I feel more confident what we are doing is correct. 

Thanks again.

**Comment by phillipd94** [comment]
Sorry for the delay here, I'm going to go ahead and close this issue as it seems to be resolved in the short term with this clarification.  If you think of any way to extend the existing interface to improve quality of life for your application while keeping with the design philosophy of the package, please let me know.
