### ISSUE TITLE
Negative length L = 0

### ISSUE THREAD

**Issue by johschmitz** [phillipd94/pyclothoids#6]
When running 

```
clothoid = Clothoid.G1Hermite(0, 0, 0, 0, 0, 1)
```
I get:

```
RuntimeError: On line: 1349 file: pyclothoids/src/Submodules/Clothoids/src/Fresnel.cc
Negative length L = 0
```

Is this an unhandled edge case?

**Comment by phillipd94** [comment]
This is a tricky case, because the clothoid we're requesting cannot exist.  The root of the problem is that the cartesian start and end points are the same, meaning we are asking for a clothoid that is self-intersecting.  Every clothoid (except the degenerate cases of circular arcs and line segments) is a scaled and rotated segment of the euler spiral, which contains no self-intersections.  Therefore, the only clothoid that could possibly have the same starting and ending cartesian coordinates is the full arc of a circle, and that would require that the start and end headings are exactly the same.  I suppose you could argue that a zero length clothoid also has the same start and end points, but it would also be bound by the same requirements that the start and end headings must be the same.  So in a sense, you're correct that this is an unhandled edge case, but there isn't exactly a clear way to handle it other than raising an exception.  I'm open to suggestions, but I think the best we could really do is catch the runtime error and raise an exception with a more helpful error message clearly explaining what has gone wrong, and call out this limitation in the docstring for the method.

**Comment by johschmitz** [comment]
Is this error message coming from the original clothoid lib? Then it should be fixed in there, not in the Python wrapper. When I wrote the issue I didn't have a good enough understanding of that architecture. Also I think the lib should distinguish between L<0 and L=0.

**Comment by phillipd94** [comment]
Yeah, this message comes from Bertolazzi's code in Fresnel.cc, I'm not sure what the desired behavior of the original clothoid library is in this case though, since a valid solution doesn't exist.

**Comment by johschmitz** [comment]
I guess it should just say something like "Negative or zero length". Or separately check the case L=0. Pretty simple.

**Comment by johschmitz** [comment]
Closing since this needs to be fixed in the C++ code.
